FROM python:3.10 AS build

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY . /app/

RUN uv sync --locked --no-dev

FROM python:3.10-alpine3.20

RUN apk update && apk add bash

COPY --from=docker:cli /usr/local/bin/docker /usr/local/bin/docker

COPY --from=build /app/ /app/

WORKDIR /app/

EXPOSE 8000

ENV PATH="/app/.venv/bin:$PATH"

CMD ["python", "-m", "mcp_anywhere", "serve", "http"]